### ISSUE TITLE
支持IP ROUTE特性

### ISSUE THREAD

**Issue by clywm520** [sigcn/pg#11]
AB建立VPN，能否支持访问各自的内网网段呢，尝试了ip route 无法生效。
@rkonfj 作者是否支持这一特性呢

**Comment by rkonfj** [comment]
使用 `--allowed-ip` 参数，让 VPN 节点成为两个 LAN 的路由器。下面是个例子：

**现有条件：**
A 节点的 LAN 为 192.168.1.23/24，路由器已加路由 100.64.0.0/24 via 192.168.1.23
B 节点的 LAN 为 192.168.2.24/24，路由器已加路由 100.64.0.0/24 via 192.168.2.24
A 节点和 B 节点系统已允许路由功能

**运行 VPN：**
A
```
sudo pgcli vpn -s wss://synf.in/pg -4 100.64.0.1/24 --allowed-ip 192.168.1.0/24
```
B
```sh
sudo pgcli vpn -s wss://synf.in/pg -4 100.64.0.2/24 --allowed-ip 192.168.2.0/24
```

> [!NOTE]
> `allowed-ip` 会被广播到所有 VPN 节点并作为路由条目，设置不当可能导致节点物理出现网络问题

**Comment by rkonfj** [comment]
90be7dccdd3892555dd593bbfa7c1bd0d34a4b90 这个提交去掉了 `--allowed-ip` 参数，并使用系统路由表。当前仅支持 Linux

请帮忙测试。谢谢

**Comment by rkonfj** [comment]
如果还有问题，随时重新打开。先关闭了
