### ISSUE TITLE
pre-shared secret file 不过期

### ISSUE THREAD

**Issue by ctaoist** [sigcn/pg#14]
希望增加不过期的功能

**Comment by rkonfj** [comment]
2 种方式颁发的 `network secret` 都可以设置有效期为 100 年或更久：

**生成预共享密钥文件使用`--duration 876500h`设置有效期**
```
pgcli admin secret --network "<email>" --duration 876500h
```
**pgmap 配置文件`config.yml`配置密钥轮转和有效期**
```
secret_rotation_period: 876500h
secret_validity_period: 876501h
```

>[!NOTE]
>因为 `pgmap` 会自动轮转密钥，推荐设置一个合适的有效期，增强安全性。

**Comment by ctaoist** [comment]
嗯，我后来也想到了，100年足够了。。。

谢谢
