### ISSUE TITLE
ip route bug

### ISSUE THREAD

**Issue by clywm520** [sigcn/pg#18]
windows客户端A，linux服务端B。
A执行命令route add 192.168.1.0 mask 255.255.255.0 192.168.8.2     访问B服务器内网。如果B服务端重启，或者异常情况断网。B重连后，A就访问不了B服务端内网段了 192.168.1.0。需要执行重新，删除，再创建才可以

**Comment by rkonfj** [comment]
`B 服务`重启后公私钥改变了，但`A 服务`仍然持有旧的公钥。`main` 分支已修复该问题。

非常感谢你的反馈！
