### ISSUE TITLE
客户端中转？

### ISSUE THREAD

**Issue by 13653216371** [sigcn/pg#19]
除了服务端中转，具备公网的客户端能中转吗？根据延迟最小选择

**Comment by rkonfj** [comment]
很好的提议。接下来会设计和实现该功能。

**Comment by 13653216371** [comment]
另外服务端有容灾的考虑吗，或者无中心模式

**Comment by rkonfj** [comment]
@13653216371 pg 本身不会直接实现高可用的服务器。

不过，可以把 pgmap 作为数据平面。另外设计一个控制平面以实现一种高可用方案。

我正在维护的一个闭源专业版本正是使用上述方案实现了转发服务器的高可用。

**Comment by rkonfj** [comment]
ce553114160054cc5e79f78c84529f6e51daf2f3

这个提交添加了 PEER_RELAY 的传输模式以支持客户端中转。至此，有 3 种传输模式：

1. UDP 直连
2. UDP Peer 转发 （随机选一个 EasyNAT 或 公网 IPv4 的 Peer）
3. Server 转发

默认情况下，会先尝试直连，否则 Peer 转发。前 2 者都不可行时，会使用 Server 转发。
