### ISSUE TITLE
Error: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by shen09gsd** [sigcn/pg#4]
这个是什么错误
我并没有用caddy反向代理pgmap用的是nginx，好像看上去也能用
现在客户机运行pgcli报以下错误，不知道什么原因
root@xx:/opt/vpn/bin# /opt/vpn/bin/pgcli vpn -s wss://我的域名/vv --ipv4 100.0.0.1/24
2024/05/26 15:24:23 INFO PeermapConnected server=wss://我的域名/vv latency=82.705006ms
Error: strconv.ParseInt: parsing "": invalid syntax

**Comment by rkonfj** [comment]
服务器会返回一些可选参数，客户端没有正确处理，稍后会修复这个问题。感谢反馈。
