### ISSUE TITLE
how to route nat?

### ISSUE THREAD

**Issue by ctermiii** [sigcn/pg#5]
The test was successful, and the speed for both punching and direct connection is very fast, capable of fully utilizing the bandwidth.
However, the NAT forwarding has not been set up yet.
--allowed-ip not worked ?

**Comment by rkonfj** [comment]
Thanks for reporting this! I'm confirmed it’s a bug and will fix it soon. Your feedback is appreciated!

**Comment by rkonfj** [comment]
@ctermiii This bug has been fixed. Please update to the latest version and let me know if you encounter any further issues.

**Comment by ctermiii** [comment]
0.5.1 fixed . --allowed-ip work as expected. thx for your hard work.
