### ISSUE TITLE
地址占用和无法出现google地址等问题

### ISSUE THREAD

**Issue by HIShengBo** [sigcn/pg#8]
问题一：
地址被占用
![56ba4a70cbdbcd15ba70225c25ae0aa](https://github.com/rkonfj/peerguard/assets/25527306/fd6d48de-0129-446b-8898-a3635bdab7a6)

问题二
windows启动服务后，无法正常显示google地址
取消任务第二次打开后就可以正常显示

**Comment by rkonfj** [comment]
> 问题一

你本机有其他服务监听 udp `:29877` 吗？

> 问题二 无法正常显示 google 地址

这是什么意思？

**Comment by HIShengBo** [comment]
> 问题1 
通过kill 端口解决了
> 问题2
启动服务后，无法正常显示google的登录地址，只能取消服务，重新启动可以显示google地址
默认启动服务的时候，有个二维码，显示的也是乱码

**Comment by rkonfj** [comment]
@hainanashu 

ab8ea6e59e76f8fcc83705066ea0f5b9c50ea01c 这个提交优化了 VPN 认证流程

帐号选择从命令行移动到了网页，并增加了`--auth-qr`参数默认不在终端显示二维码

**Comment by rkonfj** [comment]
如果还有其他问题，欢迎创建新的 issue 。关闭这个了
